### ISSUE TITLE
`Resource.rc` missing in `qpcpp-examples/posix-win32-cmake /dpp/`

### ISSUE THREAD

**Issue by stefanschober** [QuantumLeaps/qpcpp-examples#1]
The win32 resource file `Resource.rc` is missing in this example.
It can be copied from the `qwin-gui/dpp-gui` example.

Please take care of the path definitions. Replace double backslashes (`\\`) by single slash (`/`) if possible and use a utf-8 coding to stay compatible with MinGW.

**Comment by quantum-leaps** [comment]
Done.
--MMS
