### ISSUE TITLE
posix-win32-cmake/dpp example updated (GTK+)

### ISSUE THREAD

**Issue by stefanschober** [QuantumLeaps/qpcpp-examples#2]
The GTK+ version (bsp-gtk.cpp) was updated to make use of gtkmm (full featured CPP  implementation of the GUI features)
[qpcpp-examples-update.zip](https://github.com/QuantumLeaps/qpcpp-examples/files/14624705/qpcpp-examples-update.zip)

**Comment by quantum-leaps** [comment]
Done.
But some of the updated files reported "whitespace errors", such as trailing spaces, TABs, etc. Please consider using a better editor (with whitespace cleanup upon saving) or just the [qclean utility](https://www.state-machine.com/qtools/qclean.html).
--MMS
