### ISSUE TITLE
Zehpyr - CONFIG_CPLUSCPLUS renamed to CONFIG_CPP

### ISSUE THREAD

**Issue by JaeheeKwon** [QuantumLeaps/qpcpp-examples#5]
Since Zehpyr 3.3 renamed `CONFIG_CPLUSS` to `CONFIG_CPP`, the Zephyr example build fails when the latest Zephyr release is used. 

Ref: https://docs.zephyrproject.org/latest/releases/release-notes-3.3.html#:~:text=Replacement-,CONFIG_CPLUSPLUS,-CONFIG_CPP

**Comment by quantum-leaps** [comment]
The `prj.conf` files have been updated to use `CONFIG_CPP`.
--MMS
